### PR TITLE
New domain structure

### PR DESCRIPTION
**Pull request by wimvelzeboer**
Apply new domain structure.

In the first commit the minimal changes are done to resolve compiling issues
The second commit contains the change to the interface structure, where domains are extended from fflib_IDomain

---
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common-samplecode/31)

### CODE REVIEW

**Review by daveespo — CHANGES_REQUESTED** [review]
> Reviewed 10 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common-samplecode/31)* status: 10 of 24 files reviewed, 1 unresolved discussion (waiting on @wimvelzeboer)

___
*[sfdx-source/apex-common-samplecode/main/classes/domains/Accounts.cls, line 52 at r1](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common-samplecode/31#-MX47043-okok3Rk6gyc:-MX47043-okok3Rk6gyd:by1ao5w) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common-samplecode/blob/51291aa389a96af473281f640ed83dfa7538a654/sfdx-source/apex-common-samplecode/main/classes/domains/Accounts.cls#L52)):*
> ```VBA
> 	}
> 
> 	public void setDescription(String description)
> ```

@wimvelzeboer  Why wouldn't you pass SOUOW into this Domain method? By not including SOUOW as an argument to this method, it means that we need to assume every Account was dirtied by this method and load them into the SOUOW (as your new `AccountServiceImpl` does with `registerDirty`) which will cause spurious updates to LastModifiedDate and SystemModstamp when `SOUOW.commitWork()` is called. This is an undesirable side effect

I know that's how the old sample code for this scenario worked ... but now we've tried to separate concerns (Domain is a pure Apex class), we need to decide whether it's an anti-pattern or a recommended best practice to send SOUOW all the way down into the Domain to allow for more granular control of record updates. 

Thoughts?

**Comment by wimvelzeboer** [comment]
Hi @daveespo,
I deliberately did not include the unitOfWork in the domain. A domain method should iterate over all its content and not just a part of it. 
If you need to do an operation on a subset, then you first filter the domain based on a condition, resulting in new domain with just only those records, then you can use the setter method to change the value on all its contents. Here is an example:
```
List<Account> records = new List<Account>{ .... 100 records }
IAccounts domain = Accounts.newInstance(records);
IAccounts emeaAccounts = domain.selectByRegion('EMEA');  // Here you filter the account and only have the EMEA returned
emeaAccounts.setDescription('EMEA Account'); // This will change all the EMEA accounts

unitOfWork.registerDirty(emeaAccounts); // This will only register the EMEA accounts as dirty
```
alternatively you can use chaining to clean it a bit:
```
List<Account> records = new List<Account>{ .... 100 records }
unitOfWork.registerDirty(
    Accounts.newInstance(records)
        .selectByRegion('EMEA')
        .setDescription('EMEA Account')
);
```
This structure keeps the domain from knowing about anything else than itself and avoids making records unnecessarily dirty.

**Review by daveespo — APPROVED** [review]
Ok, I'm fine with this reasoning

> Reviewed 14 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common-samplecode/31#-:-M_w0p-d6fUTFH7IXq6B:b-ewa5pm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wimvelzeboer)

**Review by daveespo — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common-samplecode/31)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ImJohnMDaniel and @stohn777)

**Review by stohn777 — APPROVED** [review]

**Pull request merged**
